### ISSUE TITLE
Cool Script

### ISSUE THREAD

**Issue by inglesuniversal** [alekseykulikov/touch-action#5]
I tried your implementation inside a scroll view and it worked really nice.

I didn't see much difference on a range slider inside a web app running on Android 8.2 on a Motorola G5.

Do you think you can improve it further?

Regards

**Comment by alekseykulikov** [comment]
Thanks! 

Most of the modern browsers support `touch-action: manipulation` now, and FastClick is unnecessary. So the whole library could be:
```css
body {
  touch-action: manipulation;
}
```
Not much to improve further :)
